server:
  port: 2222

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
        #include: refresh

spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  cloud:
    config:
      fail-fast: true