server:
  port: 8081 #the default port used for zuul service

#zuul:
  #ignoredServices: '*'
  #host:
    #connect-timeout-millis: 20000
    #socket-timeout-millis: 20000
    #routes:
      #greeting-service: # service name to route
        #path: /greeting-service/** #path that will be intercepted
        #url: http://localhost:2222 #Default

zuul:
  routes:
    greeting-service:
      path: /greeting-service/**
      serviceId: greeting-service

#si utilizamos la etiqueta serviceId estaremos haciendo uso del descubrimiento de servicios a través de Ribbon.
#De esta forma se solicitará a eureka la instancias disponibles de greeting-service,
#eligiendo una de ellas y finalmente atacando al servicio expuesto

ribbon:
  eureka:
    enabled: false

greeting-service:
  ribbon:
    listOfServers: localhost:2221, localhost:2223

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
        #include: refresh
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest